[project]
name = "nginx-keeper"
version = "0.9.0"
vendor = "sysinner.com"
homepage = "https://www.sysinner.com"
description = "configuration management tool for nginx"
groups = ["dev/sys-runtime"]

[files]
allow = """LICENSE
bin/
misc/"""

[scripts]
